version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '12345'

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOSTNAME: 'db'
